import '@/app/globals.css';
import AdminNav from '@/components/Shared/AdminNav';
import { authOptions } from '@/utils/authOptions';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Giving Circle',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await getServerSession(authOptions);

	return (
		<html lang="en">
			<body className={inter.className}>
				<AdminNav session={session ? true : false}>{children}</AdminNav>
			</body>
		</html>
	);
}
